### PR TITLE
fix: use usermail to populate entityEmail

### LINKED ISSUE #140: Notification emails not received if no entityEmail exists
If an `entityEmail` is never provided by the user, when the daily notification email is triggered for that entity the email is never received (apparently it is never sent).

When a user firsts signs up and creates an account, use the email address provided for `userEmail` to populate `entityEmail` as well if an email address for `entityEmail` is not provided by the user via the `POST /signup` endpoint.

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #140

### CODE REVIEW

File: internal/app/http/controller/user.go [hunk 1]
```diff
@@ -169,7 +169,7 @@ func (handler *userHandler) signup() func(http.ResponseWriter, *http.Request) {
 			api.Respond(w, r, http.StatusBadRequest, errors.New("User email address is already registered."))
 			return
 		}
-		if logic.Entity.EmailExists(req.UserEmail) {
+		if logic.Entity.EmailExists(req.EntityEmail) {
```
Comment (geoffturk) [inline internal/app/http/controller/user.go]: I don't think we don't need entity emails to be unique. It's possible a user might create more than one entity but still want to control them through the same email address. Also, we don't check for entity email uniqueness right now when a user or admin changes an entity's email address.

**Review by geoffturk — CHANGES_REQUESTED** [review]
Remove the check for `entityEmail` being unique.

**Review by geoffturk — APPROVED** [review]
LGTM 🚀
